version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=module_user
      - POSTGRES_PASSWORD=module_password
      - POSTGRES_DB=module_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
